name: PHPPsalm
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # This is required for actions/checkout@v1
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif