name: PHPPsalm
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        run: ./vendor/bin/psalm --output-format=github